# Generated by Django 5.0.4 on 2024-05-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hero_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='decription',
            new_name='description',
        ),
    ]
