# Generated by Django 5.0.4 on 2024-05-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_decription_about_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='image_size',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='image_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
