# Generated by Django 5.0.4 on 2024-05-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hero_image_name_hero_image_size_hero_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image_size',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
