# Generated by Django 5.0.4 on 2024-05-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_about_image_name_about_image_size_about_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='image_size',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='image_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
