# Generated by Django 5.0.4 on 2024-05-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_skill_image_name_skill_image_size_skill_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image_size',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
